import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { resolve, relative, sep, dirname, delimiter, join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { parseArgs, parseEnv } from 'node:util'
import { loadEnv } from 'vite'

const BILLING_KEYS = [
  'VITE_PADDLE_CLIENT_TOKEN', 'VITE_PADDLE_ENV',
  'VITE_SUPABASE_URL', 'VITE_SUPABASE_ANON_KEY',
] as const

export function selectLocalBillingEnv(source: Record<string, string>, local: Record<string, string> = {}): Record<string, string> {
  const selected = Object.fromEntries(BILLING_KEYS.map(key => [key, source[key]?.trim() ?? '']))
  // Vercel may omit protected values. Reuse the local public key only for the same project.
  if (local.VITE_SUPABASE_URL === selected.VITE_SUPABASE_URL) {
    selected.VITE_SUPABASE_ANON_KEY ||= local.VITE_SUPABASE_ANON_KEY ?? ''
  }
  const missing = BILLING_KEYS.filter(key => !selected[key])
  if (missing.length) throw new Error(`Missing billing settings: ${missing.join(', ')}`)
  if (!['live', 'sandbox'].includes(selected.VITE_PADDLE_ENV)
    || source.PADDLE_ENV?.trim() !== selected.VITE_PADDLE_ENV) {
    throw new Error('Server and client Paddle environments must match (live or sandbox).')
  }
  const prefix = selected.VITE_PADDLE_ENV === 'live' ? 'live_' : 'test_'
  if (!selected.VITE_PADDLE_CLIENT_TOKEN.startsWith(prefix)) {
    throw new Error('Paddle client token does not match the selected environment.')
  }
  const origin = source.APP_URL?.trim() || source.VITE_SITE_URL?.trim()
  const expectedOrigin = selected.VITE_PADDLE_ENV === 'live' ? 'https://liqguard.com' : 'https://devpilgrm.liqguard.com'
  if (origin?.replace(/\/$/, '') !== expectedOrigin) {
    throw new Error('The linked deployment origin does not match the Paddle environment.')
  }
  return { ...selected, BILLING_DEV_READ_ORIGIN: expectedOrigin }
}

export function serializeLocalEnv(values: Record<string, string>): string {
  // Preserve spaces and reject interpolation or multiline values before writing.
  return Object.entries(values).map(([key, value]) => {
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key) || /[\r\n'$]/.test(value)) {
      throw new Error(`Unsupported env value format for ${key}`)
    }
    return `${key}='${value}'`
  }).join('\n') + '\n'
}

export function setupLocalBilling() {
  const { values } = parseArgs({ options: { environment: { type: 'string', default: 'development' } } })
  if (!['development', 'preview', 'production'].includes(values.environment!)) {
    throw new Error('Use --environment development, preview, or production.')
  }
  const root = process.cwd()
  if (!existsSync(resolve(root, '.vercel/project.json'))) {
    throw new Error('Link this checkout to the correct Vercel project with vercel link first.')
  }
  const ignoredDirectory = resolve(root, '.vercel')
  mkdirSync(ignoredDirectory, { recursive: true })
  const temporaryDirectory = mkdtempSync(resolve(ignoredDirectory, 'billing-setup-'))
  const sourceFile = resolve(temporaryDirectory, 'source.env')
  try {
    // Run the npm-installed CLI with Node on Windows, without a command shell.
    const windowsCli = [dirname(process.execPath), ...(process.env.PATH ?? '').split(delimiter)]
      .map(directory => join(directory, 'node_modules/vercel/dist/index.js')).find(file => existsSync(file))
    if (process.platform === 'win32' && !windowsCli) throw new Error('Install the Vercel CLI with npm install -g vercel.')
    const command = process.platform === 'win32' ? process.execPath : 'vercel'
    const args = [...(process.platform === 'win32' ? [windowsCli!] : []), 'env', 'pull', relative(root, sourceFile),
      '--environment', values.environment!, '--yes']
    const result = spawnSync(command, args, {
      cwd: root, stdio: 'pipe', encoding: 'utf8',
    })
    if (result.status !== 0) throw new Error('Vercel env download failed. Check vercel login and the linked project.')
    const selected = selectLocalBillingEnv(parseEnv(readFileSync(sourceFile, 'utf8')), loadEnv('development', root, ''))
    const target = resolve(root, '.env.development.local')
    const previous = existsSync(target) ? parseEnv(readFileSync(target, 'utf8')) : {}
    writeFileSync(target, '# Local billing settings. Generated by npm run billing:setup; never commit.\n'
      + serializeLocalEnv({ ...previous, ...selected }), { mode: 0o600 })
    console.log(`Local billing reads configured for Paddle ${selected.VITE_PADDLE_ENV} via ${selected.BILLING_DEV_READ_ORIGIN}.`)
    console.log('Saved public client settings and read-only routing to .env.development.local. Restart npm run dev.')
  } finally {
    // The path comes from mkdtemp under this checkout's ignored .vercel directory.
    if (resolve(temporaryDirectory).startsWith(ignoredDirectory + sep)) {
      rmSync(temporaryDirectory, { recursive: true, force: true })
    }
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  try { setupLocalBilling() } catch (error) {
    console.error(error instanceof Error ? error.message : 'Local billing setup failed.')
    process.exitCode = 1
  }
}
