export const calculatorExamplesCopy = {
  ko: {
    title: '계산 예제', lead: '입력부터 주문, 포지션 줄이기까지. 숫자가 어떻게 바뀌는지 살펴보세요.',
    products: { stock: '주식선물', index: '지수선물', commodity: '원자재선물' },
    names: { stock: 'Asteron Technologies 주식선물', index: 'Crestline 500 지수선물', commodity: 'Westhaven Crude 원유선물' },
    profiles: {
      stock: '미국의 대형 기술기업을 상상한 가상 상품입니다.',
      index: '미국 대표 기업 500종목으로 구성된 지수를 상상한 가상 상품입니다.',
      commodity: '북미산 경질유를 상상한 가상 상품입니다.',
    },
    assumptions: '상품명과 거래 조건은 설명을 위해 만든 가상 설정입니다. 모든 계좌 금액은 USD이며, 지수 가격은 포인트로 표시합니다. 가격과 증거금은 현재 거래 조건이 아닌 가정값입니다. 모든 단계는 롱 포지션이며, 현재가와 체결가는 같고 수수료는 제외합니다.',
    specs: {
      title: '종목 스펙 · 예제 가정', tickSize: '틱 사이즈', currency: '결제 통화', price: '현재가', multiplier: '계약 단위 / 승수',
      notional: '1계약 명목금액', maintenance: '유지증거금', initial: '개시증거금', equity: '시작 계좌 평가금액', position: '시작 보유 포지션',
      shares: '주 / 계약', barrels: '배럴 / 계약', point: '포인트', perPoint: 'USD / 포인트', perShare: 'USD / 주', perBarrel: 'USD / 배럴', perContract: 'USD / 계약', long: '롱', contracts: '계약',
    },
    contracts: '보유 계약수', liquidation: '예상 청산가',
    readOnly: '보기 전용 계산기',
    emptyScreen: '계좌·증거금 입력 전의 계산기 화면',
    marginFields: { rate: '유지증거금률·개시증거금률', perContract: '계약당 유지증거금·개시증거금' },
    focusNotes: [
      '입력할 값 · 계좌 평가금액·현재가·보유 계약수·계약승수·{margins}',
      '스펙 표와 비교 · 계약승수 · 유지증거금 · 개시증거금',
      '추가 매수 · 양수 주문 계약수 · 주문 가격',
      '일부 정리 · −{count} = {count}계약 정리 · 주문 가격',
    ],
    steps: ['최초 입력', '입력 완료', '주문하기', '포지션 줄이기'],
    descriptions: [
      '증거금 방식을 선택한 뒤 계좌 평가금액·현재가·보유 계약수를 입력하세요. 종목 스펙 표를 보고 계약승수와 {margins}도 함께 입력합니다. 사용자의 경우 계좌 평가금액, 현재가를 가능하면 한 화면에서 캡쳐하여 입력합니다.',
      '예시 숫자를 모두 넣은 모습입니다. 예상 청산가와 현재가를 비교하고, 포지션 유지에 필요한 증거금과 레버리지를 확인하세요.',
      '현재가로 추가 매수하는 주문 시뮬레이션입니다. 계약 수가 늘면 필요한 증거금과 레버리지가 커지고, 이 예제에서는 청산가가 현재가에 가까워집니다.',
      '앞 단계의 추가 주문을 반영한 상태에서 일부 계약을 매도합니다. 계약 수가 줄면 필요한 증거금과 레버리지가 낮아지고, 이 예제에서는 청산가가 현재가에서 멀어집니다.',
    ],
    rounding: '실제 계산기 패널에 예시 값을 표시했습니다. 입력과 버튼은 비활성화되어 있습니다. 금액·가격은 화면 표시 기준으로 반올림되며, 실제 체결 가능한 호가를 뜻하지 않습니다.',
  },
  en: {
    title: 'Calculation examples', lead: 'From your first inputs to adding and reducing a position. Follow the numbers at each step.',
    products: { stock: 'Stock futures', index: 'Index futures', commodity: 'Commodity futures' },
    names: { stock: 'Asteron Technologies Stock Futures', index: 'Crestline 500 Index Futures', commodity: 'Westhaven Crude Oil Futures' },
    profiles: {
      stock: 'An imagined major US technology company.',
      index: 'An imagined benchmark of 500 leading US companies.',
      commodity: 'An imagined North American light crude oil contract.',
    },
    assumptions: 'Product names and contract terms are fictional teaching examples. All account amounts are in USD; index prices are in points. Prices and margins are assumptions, not current trading terms. Each example holds a long position, fills at the current price, and excludes fees.',
    specs: {
      title: 'Contract specifications · Example assumptions', tickSize: 'Tick size', currency: 'Settlement currency', price: 'Current price', multiplier: 'Contract size / multiplier',
      notional: 'Notional value per contract', maintenance: 'Maintenance margin', initial: 'Initial margin', equity: 'Starting account equity', position: 'Starting position',
      shares: 'shares / contract', barrels: 'barrels / contract', point: 'points', perPoint: 'USD / point', perShare: 'USD / share', perBarrel: 'USD / barrel', perContract: 'USD / contract', long: 'Long', contracts: 'contracts',
    },
    contracts: 'Open contracts', liquidation: 'Est. liquidation price',
    readOnly: 'Read-only calculator',
    emptyScreen: 'Calculator before entering account and margin values',
    marginFields: { rate: 'maintenance margin rate · initial margin rate', perContract: 'maintenance margin per contract · initial margin per contract' },
    focusNotes: [
      'Enter these values · Account equity · Current price · Open contracts · Multiplier · {margins}',
      'Check the specifications · Multiplier · Maintenance margin · Initial margin',
      'Add to the position · Positive order quantity · Order price',
      'Reduce the position · −{count} closes {count} contracts · Order price',
    ],
    steps: ['First inputs', 'Completed inputs', 'Place an order', 'Reduce the position'],
    descriptions: [
      'Choose the margin method, then enter account equity, current price and open contracts. Use the specifications above to also enter the multiplier and {margins}.',
      'Here are the completed example inputs. Compare estimated liquidation price with current price, then review the required margins and leverage.',
      'Simulate buying more at the current price. More contracts require more margin and increase leverage. In this example, liquidation price moves closer to current price.',
      'Start from the position after the additional order, then sell some contracts. Required margin and leverage decrease. In this example, liquidation price moves farther from current price.',
    ],
    rounding: 'Actual calculator panels with example values. Inputs and buttons are disabled. Prices and amounts follow the calculator’s display rounding, not executable market ticks.',
  },
} as const
